wikiPy/urls.py
from django.urls import path
from . import views

app_name = 'wikiPy'

urlpatterns = [
    path('', views.home, name='home'),
    path('newTheme', views.newTheme, name='newTheme'),
    path('newArticle', views.newArticle, name='newArticle'),
    path('themeList', views.themeList, name='themeList'),
    path('articlesByTheme/<str:idTheme>', views.articlesByTheme, name='articlesByTheme'),
    path('view_article/<str:idArticle>', views.view_article, name='view_article')
    
]

wikiPython/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('wikiPy.urls'))
]

wikiPy/models.py
from django.db import models

# Create your models here.
class theme(models.Model):
    nameTheme = models.CharField(max_length=128, null=True, blank=True)
    descriptionTheme = models.CharField(max_length=512, null=True, blank=True)

class article(models.Model):
    nameArticle=models.CharField(max_length=128, null=True, blank=True)
    contentArticle= models.CharField(max_length=1024, null=True, blank=True)
    themeR = models.ForeignKey(theme, null=True, blank=True, on_delete=models.SET_NULL)
    

wikiPy/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect
from django.urls import reverse
from .models import article, theme


# Home view, obtiene la informacion de article 
def home(request):
    articleTotal = article.objects.all()
    return render(request, 'home.html',{
        'listaArticle' : articleTotal
    })


# New Theme: 
# si se obtiene el method = POST, se almacenan la informacion recibida
def newTheme(request):
    if request.method == 'POST':
        nameTheme = request.POST.get('nameTheme')
        descriptionTheme = request.POST.get('descriptionTheme')
        
        # la informacion almacenada se guarda en las variables del model theme
        theme.objects.create(
            nameTheme=nameTheme,
            descriptionTheme=descriptionTheme
        )
        #se redirige a la misma pagina 
        return HttpResponseRedirect(reverse('wikiPy:newTheme'))
    
    return render(request, 'newTheme.html')


# si se obtiene el method = POST, se almacenan la informacion recibida
def newArticle(request):
    if request.method=='POST':
        nameArticle = request.POST.get('nameArticle')
        contentArticle = request.POST.get('contentArticle')

        areaSeleccionada= request.POST.get('areaSeleccionada')
        themeObj = theme.objects.get(id=areaSeleccionada)

        #la informacion almacenada se guarda en las variables del model article
        article.objects.create(
            nameArticle=nameArticle,
            contentArticle=contentArticle,
            themeR = themeObj
        )
        #al crearse la variable, se redirige a la misma pagina  de crear nuevo articulo 
        return HttpResponseRedirect(reverse('wikiPy:newArticle'))
    
    return render(request, 'newArticle.html',{
        'listTheme' : theme.objects.all()
    })



def themeList(request):
    themeTotal = theme.objects.all()
    return render(request, 'themeList.html',{
        'listTheme' : themeTotal
    })



def articlesByTheme(request, idTheme):
    infoTheme = theme.objects.get(id=idTheme)
    listArticle = infoTheme.article_set.all()

    return render(request, 'articlesByTheme.html',{
        'objetoTheme':infoTheme,
        'listTheme': theme.objects.all(),
        'listArticle' :listArticle

    })

def view_article(request, idArticle):
    infoArticle = article.objects.get(id=idArticle)
    
    return render(request, 'view_article.html',{
        'objArticle':infoArticle,
        'listArticle' : theme.objects.all()
    }) 

wikiPy/templates/articlesByTheme.html
{%extends "layout.html"%}

{%block titulo%}
    Theme : {{ objetoTheme.nameTheme }}
{%endblock%}

{%block contenido%}
    <h1 style="margin-left: 20px">Theme: {{ objetoTheme.nameTheme}} </h1>
    <div class="p-3" style="margin-left: 10px">
       
        <div class="input-group" style="max-width: 600px; margin-bottom: 10px;">
            <input type="text" class="form-control form-control-sm" placeholder="Enter your article" aria-label="Search for your article" aria-describedby="button-addon2" style="font-size: 16px;">
            <button class="btn btn-outline-secondary" type="button" id="button-addon2" style="font-size: 16px;">Search</button>
        </div>  
    </div>
    <br>

    <!-- iteration list all the articles x  theme -->
    {%for infoArticle in listArticle%}
    <div class="card" style="width:50rem; margin-left:20px;">
        <div class="card-header">
        
        </div>
        <div class="card-body">

          <h5 class="card-title"> {{ infoArticle.nameArticle}}</h5>
          <p class="card-text"> {{ infoArticle.nameArticle}}</p>

          <!-- link to more info about each article-->
          <a href="{% url 'wikiPy:view_article' infoArticle.id %}" class="btn btn-secondary">More info</a>
        </div>

    </div>

    <br>

      {%endfor%}
    <br>


    
{%endblock%}  

wikiPy/templates/home.html
{%extends "layout.html"%}

{%block titulo%}
    WikiApp
{%endblock%}

{%block contenido%}
    <h1 style="margin-left: 20px">Welcome to WikiApp </h1>
    <div class="p-3" style="margin-left: 10px">
        <!-- Campo de búsqueda de artículo -->
        <div class="input-group" style="max-width: 600px; margin-bottom: 10px;">
            <input type="text" class="form-control form-control-sm" placeholder="Enter your article" aria-label="Search for your article" aria-describedby="button-addon2" style="font-size: 16px;">
            <button class="btn btn-outline-secondary" type="button" id="button-addon2" style="font-size: 16px;">Search</button>
        </div>
        
        <!-- Selector de tema -->
        <div style="max-width: 600px;">
            <select class="form-select" aria-label="Default select example" style="font-size: 16px;">
                <option selected>Search by theme</option>
                <option value="1">Biologia</option>
                <option value="2">Escuela</option>
                <option value="3">Matematica</option>
            </select>
        </div>
    </div>
    <br>

    <!--iteration: all the articles-->

    {%for infoArticle in listaArticle%}
    <div class="card" style="width:50rem; margin-left:20px;">
        <div class="card-header">
        
        </div>
        <div class="card-body">
          <h5 class="card-title"> {{ infoArticle.nameArticle }}</h5>
          <h6 class="fst-italic" > {{infoArticle.themeR.nameTheme }}</h6>
          <p class="card-text"> {{infoArticle.contentArticle}}</p>
          
          <!--link to more info about each article-->
          <a href="{% url 'wikiPy:view_article' infoArticle.id %}" class="btn btn-secondary">More info</a>
        </div>
      </div>
      <br>
      {%endfor%}
    <br>


    
{%endblock%}        
            
       
        
    

wikiPy/templates/layout.html
<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{%block titulo%} {%endblock%}</title>
    <!-- Bootstrap 5 CDN -->
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet">

</head>
<body>
    <div class="d-flex">
        <div class="d-flex flex-column flex-shrink-0 p-3 bg-dark text-white" style="width: 200px; min-height: 100vh;">
            <a >
                <span class="fs-4">WikiApp</span>
            </a>
            <hr>
            <!-- links to all the sections of the wiki app  -->
            <ul class="nav nav-pills flex-column mb-auto">
                <li class="nav-item">
                    <a href="{%url 'wikiPy:home'%}" class="nav-link text-white"> Home </a>
                </li>
                <li>
                    <a href="{%url 'wikiPy:themeList'%}" class="nav-link text-white"> Theme lists </a>
                </li>
                <li>
                    <a href="{%url 'wikiPy:newTheme'%}" class="nav-link text-white"> Create New Theme </a>
                </li>
                <li>
                    <a href="{%url 'wikiPy:newArticle'%}" class="nav-link text-white"> Create New Article </a>
                </li>
                
                
            </ul>
        

        </div>
        <div class="col-10">
            {%block contenido%}
            {%endblock%}
        </div>
        
    </div>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js"></script>
</body>
</html>

wikiPy/templates/newArticle.html
{%extends "layout.html"%}

{%block titulo%}
    WikiApp
{%endblock%}

{%block contenido%}
<h1 style="margin-left: 20px">Create a new article </h1>
<form class="container mt-4" method="POST" action="{%url 'wikiPy:newArticle'%}">
    {% csrf_token %}
    <div class="row justify-content-start" >
        <div class="col-md-6"> <!-- Controla el ancho de los elementos -->
            <div class="mb-3">
                <label for="exampleFormControlInput1" class="form-label">Title</label>
                <input type="text" class="form-control" id="exampleFormControlInput1" name="nameArticle">
            </div>

            <div style="max-width: 600px;">
                <label class="form-label"> Select theme </label>
                
                <select class="form-select" name="areaSeleccionada" aria-label="Default select example" style="font-size: 16px;">
                    {% for themeInfo in listTheme %}
                    <option value="{{themeInfo.id}}">{{themeInfo.nameTheme}}</option>

                    {%endfor%}
                </select>
            </div>

            <br>

            <div class="mb-3">
                <label for="exampleFormControlTextarea1" class="form-label">Content</label>
                <textarea class="form-control" id="exampleFormControlTextarea1" rows="7" name="contentArticle"></textarea>
            </div>
            


            <br>
            <br>


            <div class="d-grid gap-2 d-md-block">
                <button class="btn btn-primary" type="submit">Create Article</button>
                <button class="btn btn-secondary" type="button">Cancel</button>
              </div>

            <div>

            </div>
            
        </div>
    </div>
</form>
    
{%endblock%}   

wikiPy/templates/newTheme.html
{%extends "layout.html"%}

{%block titulo%}
    WikiApp
{%endblock%}

{%block contenido%}
<h1 style="margin-left: 20px">Create a new theme </h1>
<form class="container mt-4" method="POST" action="{%url 'wikiPy:newTheme'%}">
    {% csrf_token %}
    <div class="row justify-content-start" >
        <div class="col-md-6"> <!-- Controla el ancho de los elementos -->
            <div class="mb-3">
                <label for="exampleFormControlInput1" class="form-label">Title</label>
                <input type="text" class="form-control" id="exampleFormControlInput1" placeholder="" name="nameTheme">
            </div>
            <div class="mb-3">
                <label for="exampleFormControlTextarea1" class="form-label">Description</label>
                <textarea class="form-control" name="descriptionTheme" rows="2"></textarea>
            </div>
            <br>
            <div class="d-grid gap-2 d-md-block">
                <button class="btn btn-primary" type="submit">Create Theme</button>
                <button class="btn btn-secondary" type="button">Cancel</button>
              </div>
        </div>
    </div>
</form>
    
{%endblock%}   

wikiPy/templates/themeList.html
{%extends "layout.html"%}

{%block titulo%}
    Themes
{%endblock%}

{%block contenido%}
    <h1 style="margin-left: 20px">Theme list </h1>
    <div class="p-3" style="margin-left: 10px">
        <!-- Campo de búsqueda de artículo -->
        <div class="input-group" style="max-width: 600px; margin-bottom: 10px;">
            <input type="text" class="form-control form-control-sm" placeholder="Enter your article" aria-label="Search for your article" aria-describedby="button-addon2" style="font-size: 16px;">
            <button class="btn btn-outline-secondary" type="button" id="button-addon2" style="font-size: 16px;">Search</button>
        </div>
        
        <!-- Selector de tema -->
       
    </div>
    <br>

    
    {%for infoTheme in listTheme%}
    <div class="card" style="width:50rem; margin-left:20px;">
        <div class="card-header">
        
        </div>
        <div class="card-body">
          <h5 class="card-title"> {{ infoTheme.nameTheme}}</h5>
          <p class="card-text"> {{infoTheme.descriptionTheme}}</p>
          <a href="{% url 'wikiPy:articlesByTheme' infoTheme.id%}" class="btn btn-secondary">More info</a>
        </div>
      </div>
      <br>
      {%endfor%}
    <br>


    
{%endblock%}        
            
       
        
    

wikiPy/templates/view_article.html
{%extends "layout.html"%}

{%block titulo%}
    Article : {{ objArticle.nameArticle }}
{%endblock%}

{%block contenido%}
    <h1 style="margin-left: 20px">Article: {{ objArticle.nameArticle}} </h1>
    <div class="p-3" style="margin-left: 10px">
        <!-- Campo de búsqueda de artículo -->
        
    
        <!-- Selector de tema -->
       
    </div>
    <br>

    
    <div class="card" style="width:50rem; margin-left:20px;">
        
        <div class="card-body">
          <h5 class="card-title"> Theme: {{ objArticle.themeR.nameTheme}}</h5>
          <p class="card-text"> {{ objArticle.contentArticle}}</p>
          
        </div>
      </div>
      <br>
      <a href="{% url 'wikiPy:home'%}" class="btn btn-secondary" style="margin-left: 25px;">Go Home</a>
      <br>
    <br>


    
{%endblock%} 